name: Package and Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                npm install
                npm run build
                ls
                git add dist/*
                git status
                git commit -m "Updates from Workflow"
                git push origin :gh-pages
                git subtree push --prefix dist origin gh-pages
