name: Package and Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                npm install
                npm run build
                git add --force dist
                git status
                git commit -m "Updates from Workflow"
                git subtree push --prefix dist origin gh-pages
