name: Package and Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com
                npm install
                npm run build
                git add -A dist/*
                git status
                git commit -m "Updates from workflow"
                git status
                git push origin `git subtree split --prefix dist main`:gh-pages --force
